import React from 'react';
import { AlertTriangle, Info, X } from 'lucide-react';
import { motion } from 'framer-motion';

export type DisclaimerType = 'medical' | 'emergency' | 'ai' | 'mini' | 'full';

interface LegalDisclaimerProps {
  type: DisclaimerType;
  onClose?: () => void;
  className?: string;
}

const LegalDisclaimer: React.FC<LegalDisclaimerProps> = ({
  type,
  onClose,
  className = ''
}) => {
  // Mini disclaimer for persistent display in UI header
  if (type === 'mini') {
    return (
      <div className={`text-xs text-gray-500 ${className}`}>

        <span>AI companion · not medical advice</span>

      </div>
    );
  }

  // Medical disclaimer
  if (type === 'medical') {
    return (
      <div className={`bg-blue-50 border border-blue-100 rounded-lg p-4 ${className}`}>
        <div className="flex">
          <Info size={20} className="text-blue-500 flex-shrink-0 mt-0.5 mr-3" />
          <div className="flex-1">
            <h4 className="text-sm font-medium text-blue-800">Medical Disclaimer</h4>
            <p className="text-xs text-blue-700 mt-1">
              Soberi.ai is an informational and self-help tool only. The content and conversations provided by the service do not constitute medical advice, diagnosis, or treatment and do not create a clinician–patient relationship. Always seek the advice of a qualified health-care professional with any questions you may have regarding a medical condition or mental-health concern.
            </p>
          </div>
          {onClose && (
            <button
              onClick={onClose}
              className="flex-shrink-0 text-blue-400 hover:text-blue-600 ml-2"
              aria-label="Close disclaimer"
            >
              <X size={16} />
            </button>
          )}
        </div>
      </div>
    );
  }

  // Emergency disclaimer
  if (type === 'emergency') {
    return (
      <div className={`bg-red-50 border border-red-100 rounded-lg p-4 ${className}`}>
        <div className="flex">
          <AlertTriangle size={20} className="text-red-500 flex-shrink-0 mt-0.5 mr-3" />
          <div className="flex-1">
            <h4 className="text-sm font-medium text-red-800">Emergency Disclaimer</h4>
            <p className="text-xs text-red-700 mt-1">
              If you believe you may harm yourself or others, or are having a medical emergency, call your local emergency number (e.g., 112 in the EU/UK, 911 in the US) immediately. Soberi.ai is not a crisis-response service and cannot contact emergency services on your behalf.
            </p>
          </div>
          {onClose && (
            <button
              onClick={onClose}
              className="flex-shrink-0 text-red-400 hover:text-red-600 ml-2"
              aria-label="Close disclaimer"
            >
              <X size={16} />
            </button>
          )}
        </div>
      </div>
    );
  }

  // AI disclaimer
  if (type === 'ai') {
    return (
      <div className={`bg-amber-50 border border-amber-100 rounded-lg p-4 ${className}`}>
        <div className="flex">
          <Info size={20} className="text-amber-500 flex-shrink-0 mt-0.5 mr-3" />
          <div className="flex-1">
            <h4 className="text-sm font-medium text-amber-800">AI Disclaimer</h4>
            <p className="text-xs text-amber-700 mt-1">
              Conversations are generated by an artificial-intelligence system and may occasionally produce inaccurate, incomplete, or biased information. You are solely responsible for how you interpret and act on the content.
            </p>
          </div>
          {onClose && (
            <button
              onClick={onClose}
              className="flex-shrink-0 text-amber-400 hover:text-amber-600 ml-2"
              aria-label="Close disclaimer"
            >
              <X size={16} />
            </button>
          )}
        </div>
      </div>
    );
  }

  // Full disclaimer (all disclaimers combined)
  return (
    <div className={`space-y-4 ${className}`}>
      <div className="bg-blue-50 border border-blue-100 rounded-lg p-4">
        <h4 className="text-sm font-medium text-blue-800">Medical Disclaimer</h4>
        <p className="text-xs text-blue-700 mt-1">
          Soberi.ai is an informational and self-help tool only. The content and conversations provided by the service do not constitute medical advice, diagnosis, or treatment and do not create a clinician–patient relationship.
        </p>
      </div>

      <div className="bg-red-50 border border-red-100 rounded-lg p-4">
        <h4 className="text-sm font-medium text-red-800">Emergency Disclaimer</h4>
        <p className="text-xs text-red-700 mt-1">
          If you believe you may harm yourself or others, or are having a medical emergency, call your local emergency number (911) immediately. Soberi.ai cannot contact emergency services on your behalf.
        </p>
      </div>

      <div className="bg-amber-50 border border-amber-100 rounded-lg p-4">
        <h4 className="text-sm font-medium text-amber-800">AI Disclaimer</h4>
        <p className="text-xs text-amber-700 mt-1">
          Conversations are generated by an artificial-intelligence system and may occasionally produce inaccurate, incomplete, or biased information.
        </p>
      </div>

      {onClose && (
        <div className="flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors duration-200 text-sm"
          >
            I Understand
          </button>
        </div>
      )}
    </div>
  );
};

export default LegalDisclaimer;