import React from 'react';
import { ArrowLeft } from 'lucide-react';

interface LegalTermsViewProps {
  type: 'terms' | 'privacy' | 'ai';
  onBack: () => void;
}

const LegalTermsView: React.FC<LegalTermsViewProps> = ({ type, onBack }) => {
  return (
    <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-sm border border-gray-200 p-6">
      <div className="flex items-center mb-6">
        <button
          onClick={onBack}
          className="p-2 mr-2 rounded-full hover:bg-gray-100"
          aria-label="Go back"
        >
          <ArrowLeft size={20} className="text-gray-600" />
        </button>
        <h1 className="text-2xl font-semibold">
          {type === 'terms' && 'Terms of Service'}
          {type === 'privacy' && 'Privacy Policy'}
          {type === 'ai' && 'AI Transparency'}
        </h1>
      </div>

      <div className="prose max-w-none">
        {type === 'terms' && (
          <>
            <h2>1. Introduction</h2>
            <p>
              These Terms of Service ("Terms") govern your access to and use of Soberi.ai, including any content, functionality, and services offered through Soberi.ai (the "Service").
            </p>

            <h2>2. Medical Disclaimer</h2>
            <p>
              Soberi.ai is an informational and self-help tool only. The content and conversations provided by the service do not constitute medical advice, diagnosis, or treatment and do not create a clinician–patient relationship. Always seek the advice of a qualified health-care professional with any questions you may have regarding a medical condition or mental-health concern.
            </p>

            <h2>3. Emergency Disclaimer</h2>
            <p>
              If you believe you may harm yourself or others, or are having a medical emergency, call your local emergency number (e.g., 112 in the EU/UK, 911 in the US) immediately. Soberi.ai is not a crisis-response service and cannot contact emergency services on your behalf.
            </p>

            <h2>4. AI & Accuracy Disclaimer</h2>
            <p>
              Conversations are generated by an artificial-intelligence system and may occasionally produce inaccurate, incomplete, or biased information. You are solely responsible for how you interpret and act on the content.
            </p>

            <h2>5. No Warranties / Limitation of Liability</h2>
            <p>
              The service is provided "as is" and "as available," without warranties of any kind, express or implied. To the maximum extent permitted by law, the company disclaims all liability for losses or damages arising from your use of Soberi.ai.
            </p>

            <h2>6. Age Restriction</h2>
            <p>
              Soberi.ai is intended for users 18 years and older. If you are under 18, please do not use the service.
            </p>

            <h2>7. User-Generated Content & Moderation</h2>
            <p>
              We reserve the right to remove any content that violates these Terms or that we find objectionable for any reason. You are responsible for all content you submit to the Service.
            </p>

            <h2>8. Intellectual Property</h2>
            <p>
              "Soberi.ai" and all related logos, trademarks, and service marks are owned by us. All other trademarks, service marks, and logos used in connection with our Service are the property of their respective owners.
            </p>

            <h2>9. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. It is your responsibility to review these Terms periodically. Your continued use of the Service constitutes acceptance of any changes.
            </p>
          </>
        )}

        {type === 'privacy' && (
          <>
            <h2>1. Introduction</h2>
            <p>
              This Privacy Policy describes how we collect, use, and share your personal information when you use Soberi.ai (the "Service").
            </p>

            <h2>2. Information We Collect</h2>
            <p>
              We collect information you provide directly to us, including:
            </p>
            <ul>
              <li>Chat messages and interactions with the AI</li>
              <li>Journal entries</li>
              <li>Check-in data regarding your mood and cravings</li>
              <li>Progress tracking information</li>
              <li>Task information</li>
              <li>Device information and usage data</li>
            </ul>

            <h2>3. How We Use Your Information</h2>
            <p>
              We use your information to:
            </p>
            <ul>
              <li>Provide, maintain, and improve the Service</li>
              <li>Personalize your experience</li>
              <li>Monitor and analyze usage trends</li>
              <li>Enhance the safety and security of the Service</li>
              <li>Communicate with you about the Service</li>
            </ul>

            <h2>4. Data Storage and Security</h2>
            <p>
              Your data is stored locally on your device and synchronized with secure cloud storage when you are online. We implement appropriate technical and organizational measures to protect your personal data.
            </p>

            <h2>5. GDPR Compliance</h2>
            <p>
              For users in the European Economic Area (EEA), we process your personal data in accordance with the General Data Protection Regulation (GDPR).
            </p>
            <p>
              Lawful basis for processing:
            </p>
            <ul>
              <li>Consent: For processing health-related data</li>
              <li>Contract: To provide you with the Service</li>
              <li>Legitimate Interests: To improve our Service</li>
            </ul>

            <h2>6. Your Rights</h2>
            <p>
              Depending on your location, you may have certain rights regarding your personal information, including:
            </p>
            <ul>
              <li>Access to your personal data</li>
              <li>Correction of inaccurate data</li>
              <li>Deletion of your data</li>
              <li>Data portability</li>
              <li>Withdrawal of consent</li>
            </ul>

            <h2>7. Changes to This Privacy Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
            </p>

            <h2>8. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us at: privacy@Soberi.ai
            </p>
          </>
        )}

        {type === 'ai' && (
          <>
            <h2>1. AI Technology</h2>
            <p>
              Soberi.ai uses advanced artificial intelligence technology to provide recovery support through conversations. Our AI system is designed to offer encouragement, information, and coping strategies for addiction recovery.
            </p>

            <h2>2. How Our AI Works</h2>
            <p>
              Our AI uses natural language processing to understand your messages and generate helpful responses. The system is trained on a wide range of recovery-related information but does not provide medical advice or treatment.
            </p>

            <h2>3. AI Limitations</h2>
            <p>
              While our AI strives to provide accurate and helpful information, it has several limitations:
            </p>
            <ul>
              <li>It may occasionally generate incorrect or incomplete information</li>
              <li>It cannot diagnose medical conditions or provide personalized medical advice</li>
              <li>It cannot contact emergency services if you are in crisis</li>
              <li>It may not always understand complex emotional states or nuanced situations</li>
            </ul>

            <h2>4. Data Usage for AI Improvement</h2>
            <p>
              With your permission, we may use anonymized conversations to improve our AI system. All personal identifiers are removed before any data is used for training or improvement purposes.
            </p>

            <h2>5. Human Oversight</h2>
            <p>
              Our system includes human oversight processes to review and improve AI responses, especially for sensitive topics. Any human review of conversations is conducted with strict privacy protocols.
            </p>

            <h2>6. EU AI Act Compliance</h2>
            <p>
              Soberi.ai is designed to comply with the EU AI Act requirements for high-risk AI systems, including risk assessment, bias monitoring, and technical documentation.
            </p>
          </>
        )}
      </div>
    </div>
  );
};

export default LegalTermsView;